##########################
#个人配置
##########################
com:
 spdb:
  lvlj:
    name: testing
    title: spring boot demo
    desc: ${com.spdb.lvlj.name} is lenrning ${com.spdb.lvlj.title} #引用别的配置
  hxl:
    value: ${random.value} # 随机字符串
    number: ${random.int} # 随机int
    bignumber: ${random.long} # 随机long
    test1: ${random.int(10)} # 10以内的随机数
    test2: ${random.int[10,20]} # 10-20的随机数
